export const APPWRITE = {
  endpoint: process.env.APPWRITE_ENDPOINT ?? "https://cloud.appwrite.io/v1",
  projectId: process.env.APPWRITE_PROJECT_ID ?? "",
  databaseId: process.env.APPWRITE_DATABASE_ID ?? "workspace",
  collections: {
    userPreferences: "user_preferences",
    notes: "notes",
    boards: "boards",
    researchWorkspaces: "research_workspaces",
    vault: "secret_vault_entries",
    knowledgeItems: "knowledge_items",
    knowledgeChunks: "knowledge_chunks",
    knowledgeItemVersions: "knowledge_item_versions",
    knowledgeSearchHistory: "knowledge_search_history",
    leads: "leads",
    customLeadFields: "custom_lead_fields",
    leadColumnConfigs: "lead_column_configs",
    terminalCommands: "terminal_commands",
    apps: "apps",
    usefulLinks: "useful_links",
    chatSessions: "chat_sessions",
    chatMessages: "chat_messages",
    documents: "documents",
    importedFiles: "imported_files",
    mailAccounts: "mail_accounts",
    integrations: "integrations",
    taskRuns: "task_runs",
    taskRunEvents: "task_run_events",
    verificationJobs: "verification_jobs",
    entities: "entities",
    relations: "relations",
    workingMemory: "working_memory",
    emailDrafts: "email_drafts",
    emailAttachments: "email_attachments",
    miroActivity: "miro_activity",
    notionActivity: "notion_activity",
    todoistTasks: "todoist_tasks",
    auditLogs: "audit_logs",
    activities: "activities",
    mailMessages: "mail_messages",
    users: "users",
    affineWorkspaces: "affine_workspaces",
    notifications: "notifications",
    searchVectors: "search_vectors",
    agentJobs: "agent_jobs",
    researchLabItems: "research_lab_items",
    workSessions: "work_sessions",
  },
} as const
