import type { UniversalOpportunity } from "./types"

export const MOCK_OPPORTUNITIES: UniversalOpportunity[] = [
  {
    id: "opp_saas_01",
    prospect: {
      name: "Marcus Vance",
      title: "VP of Growth & Engineering",
      email: "marcus.vance@databridge.io",
      phone: "+1 (415) 890-2144",
      linkedin_url: "https://linkedin.com/in/marcusvance",
      location: "San Francisco, CA",
    },
    account: {
      name: "DataBridge Systems",
      domain: "databridge.io",
      industry: "B2B SaaS / Enterprise Infrastructure",
      size: "120-250 employees",
      revenue_range: "$18M - $25M ARR",
      tech_stack: ["Next.js", "PostgreSQL", "Temporal", "KumoMTA", "Cloudflare"],
      description: "Real-time data synchronization engine connecting fragmented ERPs and analytical data lakes.",
    },
    fit_score: 96,
    fit_reasons: [
      "Actively scaling sales engineering team (+6 job openings this month)",
      "High tech affinity with distributed systems & custom MTA architecture",
      "Recent Series B funding announcement ($22M led by Bessemer)",
    ],
    need: "Replacing brittle outbound email scripts and fragmented CRM silos with a unified, high-deliverability acquisition operating system.",
    buying_signals: [
      {
        id: "sig_1",
        signal: "Posted on LinkedIn seeking solutions for high-volume ESMTP deliverability",
        source: "LinkedIn Post Analysis",
        confidence: "high",
        timestamp: "2 hours ago",
      },
      {
        id: "sig_2",
        signal: "Hiring 4 Outbound Enterprise BDRs",
        source: "Careers Page Crawler",
        confidence: "high",
        timestamp: "1 day ago",
      },
    ],
    intent: {
      level: "high",
      detected_intent: "ready_to_book",
      confidence: 0.94,
    },
    stage: "high_intent",
    research_dossier: {
      summary: "DataBridge recently expanded their GTM team but their existing cold outreach inbox placement dropped by 34% after domain reputation issues on their secondary domains.",
      key_initiatives: [
        "Migrating outreach from third-party shared IPs to dedicated KumoMTA mail nodes",
        "Scaling personalized technical outreach to VP-level data engineers",
      ],
      pain_points: [
        "Shared IP pooling causing false-positive spam filtering at Outlook 365 tenants",
        "SDRs spending 14+ hours/week writing custom research briefs manually",
      ],
      recommended_angle: "Focus on automated pre-send deliverability gating, 2048-bit RSA DKIM signing, and authentic MUA header emulation.",
      evidence: [
        {
          title: "Public DMARC Record Audit",
          quote: "p=none policy with missing rua/ruf aggregation addresses on databridge-outreach.com",
          url: "https://dmarcly.com/audit/databridge.io",
        },
      ],
    },
    conversation: {
      thread_id: "conv_databridge_101",
      messages_count: 3,
      latest_message: {
        from: "Marcus Vance",
        text: "This infrastructure breakdown is exactly what our infra team has been debating. Can we grab 15 minutes tomorrow afternoon to walk through the DKIM shaping?",
        timestamp: "24m ago",
        direction: "inbound",
      },
      thread: [
        {
          id: "m_1",
          direction: "outbound",
          from: "hello@nasrullahtanim.me",
          to: "marcus.vance@databridge.io",
          subject: "Marcus - DataBridge outreach infrastructure observation",
          body: "Hi Marcus,\n\nI was reviewing DataBridge's recent GTM expansion and noticed your secondary sending subdomains are missing strict DMARC alignment, which often triggers silent filtering on enterprise Microsoft 365 mailboxes.\n\nWe engineered SlideIn to route through dedicated KumoMTA submission with authentic Apple Mail MUA fingerprints and automatic pre-send placement gates.\n\nWould a 5-minute technical blueprint be helpful for your team?",
          timestamp: "Yesterday, 10:30 AM",
          deliverability_grade: "A (100/100)",
        },
        {
          id: "m_2",
          direction: "inbound",
          from: "marcus.vance@databridge.io",
          to: "hello@nasrullahtanim.me",
          subject: "Re: Marcus - DataBridge outreach infrastructure observation",
          body: "This infrastructure breakdown is exactly what our infra team has been debating. Can we grab 15 minutes tomorrow afternoon to walk through the DKIM shaping?",
          timestamp: "24m ago",
          intent_detected: "ready_to_book (94% confidence)",
        },
      ],
    },
    next_best_action: {
      action: "Send 1-click live calendar invite for tomorrow at 2:30 PM PT",
      reason: "Prospect confirmed high buying intent and requested meeting time.",
      suggested_draft: {
        subject: "Re: Marcus - DataBridge outreach infrastructure observation",
        body: "Hi Marcus,\n\nGlad this resonated! You can grab 15 minutes directly on my calendar here:\nhttps://cal.com/nasrullah-tanim/tech-eval\n\nI will have our technical architecture diagram ready to share.\n\nBest,\nNasrullah",
        deliverability_score: 100,
      },
      cta_type: "send_booking_link",
    },
    vertical_attributes: {
      product_tier: "Enterprise Pro",
      tech_stack_match: "High (Temporal + Go)",
      estimated_deal_size: "$4,200 / mo",
    },
    assigned_agent: "Conversation Agent (Alpha)",
    created_at: "2026-10-04T12:00:00Z",
    updated_at: "2026-10-06T03:30:00Z",
  },
  {
    id: "opp_agency_02",
    prospect: {
      name: "Elena Rostova",
      title: "Managing Partner",
      email: "elena@vanguardscale.com",
      phone: "+1 (212) 555-0192",
      linkedin_url: "https://linkedin.com/in/elenarostova",
      location: "New York, NY",
    },
    account: {
      name: "Vanguard Scale Agency",
      domain: "vanguardscale.com",
      industry: "Performance Marketing & B2B Growth Agency",
      size: "35-50 team members",
      revenue_range: "$5M - $8M ARR",
      tech_stack: ["HubSpot", "Instantly", "Webflow", "Stripe"],
      description: "Growth partner for mid-market e-commerce and fintech brands scaling from $10M to $50M GMV.",
    },
    fit_score: 91,
    fit_reasons: [
      "Managing acquisition across 18 concurrent client accounts",
      "Experiencing high churn due to shared mailbox deliverability drops",
      "Looking for white-label acquisition OS to offer clients as a $1,000 onboarding package",
    ],
    need: "Deploying multi-tenant, branded acquisition workspaces for 20+ clients under their agency umbrella.",
    buying_signals: [
      {
        id: "sig_3",
        signal: "Visited 'Multi-Tenant Agency White-Label' documentation page 3 times",
        source: "Website Telemetry",
        confidence: "high",
        timestamp: "3 hours ago",
      },
    ],
    intent: {
      level: "high",
      detected_intent: "asking_pricing_and_terms",
      confidence: 0.89,
    },
    stage: "qualified",
    research_dossier: {
      summary: "Elena runs high-ticket agency retainers ($6k-$12k/mo). Their primary bottleneck is onboarding new client domains and warming them up without burning 4-6 weeks of retainer runway.",
      key_initiatives: [
        "Transitioning clients to autonomous AI acquisition workflows",
        "Automating prospect research briefs directly into client Slack channels",
      ],
      pain_points: [
        "Manual domain DNS configuration takes 3 days per client",
        "Clients asking for real-time conversation transparency without logging into complex sales tools",
      ],
      recommended_angle: "Emphasize SlideIn's 1-click workspace provisioning, DNS pre-check automation, and client command center view.",
      evidence: [
        {
          title: "Agency Case Study Review",
          quote: "Average time-to-first-lead for new clients is currently 28 days.",
          url: "https://vanguardscale.com/case-studies",
        },
      ],
    },
    conversation: {
      thread_id: "conv_vanguard_202",
      messages_count: 2,
      latest_message: {
        from: "Elena Rostova",
        text: "How quickly can we provision 10 isolated workspaces for our Q4 cohort?",
        timestamp: "1 hour ago",
        direction: "inbound",
      },
      thread: [
        {
          id: "m_3",
          direction: "outbound",
          from: "hello@nasrullahtanim.me",
          to: "elena@vanguardscale.com",
          subject: "Elena - multi-tenant acquisition workspaces for Vanguard",
          body: "Hi Elena,\n\nSaw Vanguard's impressive work scaling fintech cohorts this quarter. When managing 15+ client domains simultaneously, keeping reputations strictly isolated usually becomes an operational bottleneck.\n\nSlideIn gives each client their own branded workspace, dedicated KumoMTA DKIM signing, and automated peer-to-peer warmup.\n\nWould it help to see how an agency cohort workspace is configured?",
          timestamp: "Yesterday, 2:15 PM",
          deliverability_grade: "A (100/100)",
        },
        {
          id: "m_4",
          direction: "inbound",
          from: "elena@vanguardscale.com",
          to: "hello@nasrullahtanim.me",
          subject: "Re: Elena - multi-tenant acquisition workspaces for Vanguard",
          body: "How quickly can we provision 10 isolated workspaces for our Q4 cohort?",
          timestamp: "1 hour ago",
          intent_detected: "asking_pricing_and_terms (89% confidence)",
        },
      ],
    },
    next_best_action: {
      action: "Reply with automated workspace provisioning walkthrough & demo sandbox link",
      reason: "Prospect is in late qualification stage evaluating deployment velocity.",
      suggested_draft: {
        subject: "Re: Elena - multi-tenant acquisition workspaces for Vanguard",
        body: "Hi Elena,\n\nWorkspaces are created via API or dashboard in under 3 seconds with automated DNS templates for Cloudflare/Namecheap.\n\nHere is a 3-minute sandbox overview: https://slidein.me/agency-demo\n\nHappy to spin up a staging workspace for Vanguard if you have 10 minutes to connect.",
        deliverability_score: 98,
      },
      cta_type: "send_followup",
    },
    vertical_attributes: {
      agency_retainer_tier: "Tier 1 Agency Partner",
      client_workspaces_requested: 10,
      monthly_pipeline_potential: "$3,500 / mo",
    },
    assigned_agent: "Personalization Agent (Beta)",
    created_at: "2026-10-05T08:00:00Z",
    updated_at: "2026-10-06T02:45:00Z",
  },
  {
    id: "opp_mortgage_03",
    prospect: {
      name: "Austin Miller",
      title: "Senior Homebuyer / Investor",
      email: "borrower.austin.miller@gmail.com",
      phone: "+1 (512) 771-9023",
      location: "Austin, TX",
    },
    account: {
      name: "Private Buyer / Refinance Client",
      domain: "gmail.com",
      industry: "Residential Real Estate / Lending",
      size: "Individual Buyer",
      description: "Qualified borrower evaluating $620k conventional purchase loan in Travis County, TX.",
    },
    fit_score: 98,
    fit_reasons: [
      "Completed full mortgage amortization calculation on branded advisor funnel",
      "Target purchase timeline is 30-60 days with active realtor engagement",
      "Credit score tier is 750+ with 20% down payment readiness",
    ],
    need: "Securing competitive 30-year fixed rate and pre-approval letter for immediate property offer.",
    buying_signals: [
      {
        id: "sig_4",
        signal: "Submitted loan calculator for Single Family Home ($620,000)",
        source: "Funnel Ingest Webhook",
        confidence: "high",
        timestamp: "10m ago",
      },
    ],
    intent: {
      level: "high",
      detected_intent: "ready_to_book",
      confidence: 0.96,
    },
    stage: "booked",
    research_dossier: {
      summary: "Austin calculated a $620,000 purchase with estimated monthly payment ~$3,975/mo. Responded within 4 minutes confirming ready to review scenarios.",
      key_initiatives: ["Securing pre-approval letter for weekend open house"],
      pain_points: ["Wants to compare rate lock vs floating with current bond yields"],
      recommended_angle: "Offer immediate 15-min scenario review with live rate comparison sheet.",
      evidence: [
        {
          title: "Funnel Telemetry",
          quote: "Down payment: 20%, Credit score: 760, Purchase timeframe: 30 days.",
        },
      ],
    },
    conversation: {
      thread_id: "conv_austin_303",
      messages_count: 3,
      latest_message: {
        from: "Nasrullah Tanim",
        text: "Confirmed on calendar for Thursday at 11:00 AM CST. Looking forward to reviewing your options, Austin!",
        timestamp: "5m ago",
        direction: "outbound",
      },
      thread: [
        {
          id: "m_5",
          direction: "outbound",
          from: "hello@nasrullahtanim.me",
          to: "borrower.austin.miller@gmail.com",
          subject: "Austin - your mortgage breakdown (Single Family Home)",
          body: "Hi Austin,\n\nI just pulled the numbers based on your calculation for the Single Family Home (est. $620,000 loan amount).\n\nQuick Overview:\n• Estimated Rate: ~6.625% (30-Yr Fixed Conventional)\n• Est. Principal & Interest: ~$3,972.45/mo\n• Estimated Property Tax & Insurance: ~$775.00/mo\n\nAre you actively shopping for a home right now, or just scoping out your price range for later this year?\n\nBest,\nNasrullah Tanim",
          timestamp: "Today, 10:00 AM",
          deliverability_grade: "A (100/100)",
        },
        {
          id: "m_6",
          direction: "inbound",
          from: "borrower.austin.miller@gmail.com",
          to: "hello@nasrullahtanim.me",
          subject: "Re: Austin - your mortgage breakdown (Single Family Home)",
          body: "That monthly payment looks great! We found a property in South Austin and are making an offer this week. Can you send a calendar link to talk tomorrow?",
          timestamp: "Today, 10:08 AM",
          intent_detected: "ready_to_book (96% confidence)",
        },
        {
          id: "m_7",
          direction: "outbound",
          from: "hello@nasrullahtanim.me",
          to: "borrower.austin.miller@gmail.com",
          subject: "Re: Austin - your mortgage breakdown (Single Family Home)",
          body: "Hi Austin,\n\nSounds great! You can select a 15-minute slot directly on my calendar:\nhttps://cal.com/nasrullah-tanim/mortgage-consult\n\nLooking forward to speaking with you.\n\nBest,\nNasrullah Tanim",
          timestamp: "Today, 10:09 AM",
          deliverability_grade: "A (100/100)",
        },
      ],
    },
    next_best_action: {
      action: "Prepare pre-qualification calculation sheet before Thursday 11:00 AM call",
      reason: "Meeting is confirmed. Advisor needs preliminary amortization comparison ready.",
      cta_type: "confirm_meeting",
    },
    vertical_attributes: {
      loan_amount: 620000,
      property_type: "Single Family Home",
      credit_score_tier: "760+",
      ltv: "80%",
    },
    assigned_agent: "Booking Agent (Gamma)",
    created_at: "2026-10-06T02:00:00Z",
    updated_at: "2026-10-06T03:32:00Z",
  },
]
